In [8]:
import os
os.chdir('C:/Users/saravana.ayyappa/Desktop/Machine Learning/Data')

import pandas as pd
import matplotlib.pyplot as plt
df= pd.read_csv('Sales.csv',index_col=[1])
df.head()

,Fiscal_Week,Onlineunit,Visits,Offline_Units_Queue,Calls,Cat_DM,aff_pl,OA_LU,Search_LU,PRU_log,...,Green_Monday_Online,JBF_Online.Offline_Units,Memorial_Day,Pre.Memorial_OnlineUnits,Q3_Decline_Flag,Q2wk1_decline,Aff_Transf_till20Q1,LT_2_onlineunits,LT_1__onlineunits,OA_Cap
Date,,,,,,,,,,,,,,,,,,,,,
05-01-2015,FY15 Q1 W01,22336.0,2850927.0,NaN,12997.0,4300000.0,211519.0,759142.0,558487.0,6.552508,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12-01-2015,FY15 Q1 W02,24637.0,2940060.0,NaN,14333.0,4300000.0,213968.0,1041246.0,629141.0,6.552508,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19-01-2015,FY15 Q1 W03,33898.0,3218101.0,NaN,16209.0,0.0,268325.0,739661.0,705070.0,6.470800,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26-01-2015,FY15 Q1 W04,21764.0,2916134.0,NaN,12179.0,0.0,209867.0,652412.0,592983.0,6.591674,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-02-2015,FY15 Q1 W05,23002.0,3090675.0,NaN,12388.0,0.0,231700.0,541207.0,474094.0,6.590301,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
df['diffS']=df['Onlineunit'].diff()
df['diffM']=df['Visits'].diff()
df['diffC']=df['Calls'].diff()
df['lag']=df['diffM'].shift()
df['lag2']=df['diffC'].shift()

df.dropna(inplace=True)
model3=sm.tsa.ARIMA(endog=df['Onlineunit'],exog=df[['lag'],['lag2']],order=[1,1,0])
results3=model3.fit()
print(results3.summary())

TypeError: unhashable type: 'list'